// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SISLAB.Modules.Identity.Infrastructure.Persistence;

#nullable disable

namespace SISLAB.Modules.Identity.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    partial class IdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SISLAB.Modules.Identity.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TaxId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_companies_name");

                    b.ToTable("companies", "identity");
                });

            modelBuilder.Entity("SISLAB.Modules.Identity.Domain.Companies.CompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("LumenUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("lumen_user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_memberships");

                    b.HasIndex("LumenUserId")
                        .HasDatabaseName("ix_company_memberships_lumen_user_id");

                    b.HasIndex("CompanyId", "LumenUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_memberships_company_user");

                    b.ToTable("company_memberships", "identity");
                });

            modelBuilder.Entity("SISLAB.Modules.Identity.Domain.Companies.CompanyMembership", b =>
                {
                    b.HasOne("SISLAB.Modules.Identity.Domain.Companies.Company", null)
                        .WithMany("Memberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_companies_company_id");
                });

            modelBuilder.Entity("SISLAB.Modules.Identity.Domain.Companies.Company", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
