// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SISLAB.Modules.Agenda.Infrastructure.Persistence;

#nullable disable

namespace SISLAB.Modules.Agenda.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AgendaDbContext))]
    [Migration("20260720131222_AddColorToAgendaEntry")]
    partial class AddColorToAgendaEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agenda")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SISLAB.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Bioterium.BioteriumAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AssignmentDate")
                        .HasColumnType("date")
                        .HasColumnName("assignment_date");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("ResponsibleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsible_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SwapReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("swap_reason");

                    b.Property<string>("SwappedFromName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("swapped_from_name");

                    b.HasKey("Id")
                        .HasName("pk_bioterium_assignments");

                    b.HasIndex("CompanyId", "AssignmentDate")
                        .HasDatabaseName("ix_bioterium_assignments_company_date");

                    b.ToTable("bioterium_assignments", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Entries.AgendaEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("activity_type");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_utc");

                    b.Property<Guid?>("ExperimentId")
                        .HasColumnType("uuid")
                        .HasColumnName("experiment_id");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_day");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("recurrence_rule");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_id");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("_excludedDates")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("excluded_dates");

                    b.HasKey("Id")
                        .HasName("pk_agenda_entries");

                    b.HasIndex("CompanyId", "ActivityType")
                        .HasDatabaseName("ix_agenda_entries_company_activity");

                    b.HasIndex("CompanyId", "StartDateUtc")
                        .HasDatabaseName("ix_agenda_entries_company_start");

                    b.ToTable("agenda_entries", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Presentations.Presentation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Doi")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("doi");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PresenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("presenter_name");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reminder_sent_at");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_presentations");

                    b.HasIndex("CompanyId", "ScheduledDate")
                        .HasDatabaseName("ix_presentations_company_date");

                    b.ToTable("presentations", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Rooms.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("activity");

                    b.Property<string>("BookedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("booked_by_name");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("HasConflictWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("has_conflict_warning");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("CompanyId", "Date")
                        .HasDatabaseName("ix_bookings_company_date");

                    b.HasIndex("CompanyId", "RoomId", "Date")
                        .HasDatabaseName("ix_bookings_company_room_date");

                    b.ToTable("bookings", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_rooms_company_id_id");

                    b.ToTable("rooms", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Subscriptions.IcalSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("Token")
                        .HasColumnType("uuid")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_ical_subscriptions");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ux_ical_subscriptions_token");

                    b.HasIndex("CompanyId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_ical_subscriptions_company_user");

                    b.ToTable("ical_subscriptions", "agenda");
                });

            modelBuilder.Entity("SISLAB.Modules.Agenda.Domain.Entries.AgendaEntry", b =>
                {
                    b.OwnsMany("SISLAB.Modules.Agenda.Domain.Entries.EntryReminder", "Reminders", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("MinutesBefore")
                                .HasColumnType("integer")
                                .HasColumnName("minutes_before");

                            b1.Property<string>("NotificationType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("notification_type");

                            b1.Property<Guid>("entry_id")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("entry_id")
                                .HasDatabaseName("ix_entry_reminders_entry_id");

                            b1.ToTable("entry_reminders", "agenda");

                            b1.WithOwner()
                                .HasForeignKey("entry_id")
                                .HasConstraintName("fk_entry_reminder_agenda_entries_agenda_entry_id");
                        });

                    b.Navigation("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
