// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SISLAB.Modules.Inventory.Infrastructure.Persistence;

#nullable disable

namespace SISLAB.Modules.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260712005433_AddInventoryReadModels")]
    partial class AddInventoryReadModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SISLAB.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_on_utc");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", "inventory");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.Equipments.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("asset_tag");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("StorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_location_id");

                    b.HasKey("Id")
                        .HasName("pk_equipment");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_equipment_company_id_id");

                    b.ToTable("equipment", "inventory");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.Partners.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Document")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("document");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_partners_company_id_id");

                    b.ToTable("partners", "inventory");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.StockItems.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Application")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("application");

                    b.Property<string>("Brand")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("ContainerState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("container_state");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_controlled");

                    b.Property<string>("Lot")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lot_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_location_id");

                    b.ComplexProperty<Dictionary<string, object>>("MinimumQuantity", "SISLAB.Modules.Inventory.Domain.StockItems.StockItem.MinimumQuantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("minimum_quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("minimum_quantity_amount");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Quantity", "SISLAB.Modules.Inventory.Domain.StockItems.StockItem.Quantity#Quantity", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("quantity_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("quantity_amount");
                        });

                    b.HasKey("Id")
                        .HasName("pk_stock_items");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_stock_items_company_id_id");

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_storage_locations");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_storage_locations_company_id_id");

                    b.ToTable("storage_locations", "inventory");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.Equipments.Equipment", b =>
                {
                    b.OwnsOne("SISLAB.Modules.Inventory.Domain.Equipments.CalibrationSchedule", "Calibration", b1 =>
                        {
                            b1.Property<Guid>("EquipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("LastCalibration")
                                .HasColumnType("date")
                                .HasColumnName("last_calibration");

                            b1.Property<DateOnly?>("NextCalibration")
                                .HasColumnType("date")
                                .HasColumnName("next_calibration");

                            b1.HasKey("EquipmentId");

                            b1.ToTable("equipment", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("EquipmentId");
                        });

                    b.OwnsMany("SISLAB.Modules.Inventory.Domain.Equipments.MaintenanceRecord", "MaintenanceRecords", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<long>("id"));

                            b1.Property<DateOnly>("Date")
                                .HasColumnType("date")
                                .HasColumnName("date");

                            b1.Property<string>("Notes")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("notes");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("type");

                            b1.Property<Guid>("equipment_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("equipment_id");

                            b1.ToTable("equipment_maintenances", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("equipment_id");
                        });

                    b.Navigation("Calibration");

                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.Partners.Partner", b =>
                {
                    b.OwnsMany("SISLAB.Modules.Inventory.Domain.Partners.SampleNote", "Samples", b1 =>
                        {
                            b1.Property<Guid>("partner_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Reference")
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("reference");

                            b1.Property<string>("Status")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("status");

                            b1.HasKey("partner_id", "Reference");

                            b1.ToTable("partner_samples", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("partner_id");
                        });

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.StockItems.StockItem", b =>
                {
                    b.OwnsOne("SISLAB.Modules.Inventory.Domain.ValueObjects.ExpiryDate", "Expiry", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("expiry_month");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("expiry_year");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId");
                        });

                    b.Navigation("Expiry");
                });

            modelBuilder.Entity("SISLAB.Modules.Inventory.Domain.StorageLocations.StorageLocation", b =>
                {
                    b.OwnsOne("SISLAB.Modules.Inventory.Domain.ValueObjects.TemperatureRange", "TemperatureRange", b1 =>
                        {
                            b1.Property<Guid>("StorageLocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("MaximumCelsius")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_max");

                            b1.Property<decimal>("MinimumCelsius")
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_min");

                            b1.HasKey("StorageLocationId");

                            b1.ToTable("storage_locations", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StorageLocationId");
                        });

                    b.Navigation("TemperatureRange");
                });
#pragma warning restore 612, 618
        }
    }
}
