// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SISLAB.Modules.Configuration.Infrastructure.Persistence;

#nullable disable

namespace SISLAB.Modules.Configuration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ConfigurationDbContext))]
    partial class ConfigurationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("configuration")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.ExpiryPolicies.ExpiryPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<int>("WarningWindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("warning_window_days");

                    b.HasKey("Id")
                        .HasName("pk_expiry_policies");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("ux_expiry_policies_company_id");

                    b.ToTable("expiry_policies", "configuration");
                });

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.ItemCategories.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("aliases");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<bool>("IsControlled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_controlled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_item_categories");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_item_categories_company_id_id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_item_categories_company_id_name");

                    b.ToTable("item_categories", "configuration");
                });

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.ReferenceRanges.ReferenceRange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Analyte")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("analyte");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("species");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_reference_ranges");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_reference_ranges_company_id_id");

                    b.HasIndex("CompanyId", "Analyte", "Species")
                        .IsUnique()
                        .HasDatabaseName("ux_reference_ranges_company_id_analyte_species");

                    b.ToTable("reference_ranges", "configuration");
                });

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresAuthorization")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_authorization");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_rooms_company_id_id");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_company_id_name");

                    b.ToTable("rooms", "configuration");
                });

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.Units.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_units");

                    b.HasIndex("CompanyId", "Id")
                        .HasDatabaseName("ix_units_company_id_id");

                    b.HasIndex("CompanyId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_units_company_id_symbol");

                    b.ToTable("units", "configuration");
                });

            modelBuilder.Entity("SISLAB.Modules.Configuration.Domain.ReferenceRanges.ReferenceRange", b =>
                {
                    b.OwnsOne("SISLAB.Modules.Configuration.Domain.ReferenceRanges.RangeBounds", "Bounds", b1 =>
                        {
                            b1.Property<Guid>("ReferenceRangeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal?>("Maximum")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("maximum");

                            b1.Property<decimal?>("Minimum")
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("minimum");

                            b1.HasKey("ReferenceRangeId");

                            b1.ToTable("reference_ranges", "configuration");

                            b1.WithOwner()
                                .HasForeignKey("ReferenceRangeId");
                        });

                    b.Navigation("Bounds")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
