using FluentValidation;
using SISLAB.Modules.Identity.Contracts.Onboarding;
using SISLAB.Modules.Identity.Domain.Companies;
using SISLAB.SharedKernel.Exceptions;
using SISLAB.SharedKernel.Messaging;

namespace SISLAB.Modules.Identity.Application.Onboarding;

/// <summary>
/// Self-service laboratory signup (card [E12] #75a): provisions a brand-new tenant and its founding
/// coordinator in one anonymous operation. Public because a new lab has neither an account nor an active
/// company yet — the whole point is to create both.
///
/// <para><b>Orchestration (Application layer):</b> the handler coordinates two stores that have no shared
/// transaction — Lumen's identity/authorization store and SISLAB's tenancy store — in the order that leaves
/// no orphan tenant on failure:</para>
/// <list type="number">
///   <item>reject up front if the company name or the coordinator e-mail is already taken (fast conflict);</item>
///   <item>create the coordinator user in Lumen (active), obtaining its id — if this fails, nothing else ran;</item>
///   <item><see cref="Company.Register"/> the tenant bound to that coordinator (adds the founding membership
///     and raises <c>CompanyCreated</c>), persisted via the module's unit of work / <c>TransactionBehavior</c>;</item>
///   <item>grant the coordinator company-scoped access (Lumen profile), idempotently.</item>
/// </list>
///
/// <para>The command carries no <c>CompanyId</c>: signup runs with no active tenant, and the new tenant's id is
/// generated by the aggregate. Uniqueness violations surface as <see cref="ConflictException"/> (HTTP 409);
/// field-shape problems as validation errors (HTTP 400/422).</para>
/// </summary>
/// <param name="CompanyName">Name of the laboratory/company to create; unique among active companies.</param>
/// <param name="TaxId">Optional tax identifier of the company.</param>
/// <param name="CoordinatorEmail">Coordinator's e-mail (login); unique in Lumen Identity.</param>
/// <param name="CoordinatorUsername">Coordinator's display/user name.</param>
/// <param name="CoordinatorPassword">Coordinator's password; must satisfy Lumen's password policy.</param>
public sealed record SignupCompanyCommand(
    string CompanyName,
    string? TaxId,
    string CoordinatorEmail,
    string CoordinatorUsername,
    string CoordinatorPassword) : ICommand<SignupCompanyResult>;

/// <summary>Outcome of a successful signup: the identifiers of the created tenant and its coordinator.</summary>
/// <param name="CompanyId">Identity of the newly created company.</param>
/// <param name="CoordinatorUserId">Lumen user id of the created coordinator.</param>
public sealed record SignupCompanyResult(Guid CompanyId, Guid CoordinatorUserId);

internal sealed class SignupCompanyCommandValidator : AbstractValidator<SignupCompanyCommand>
{
    public SignupCompanyCommandValidator()
    {
        RuleFor(command => command.CompanyName).NotEmpty().MaximumLength(200);
        RuleFor(command => command.TaxId).MaximumLength(20);
        RuleFor(command => command.CoordinatorEmail).NotEmpty().EmailAddress().MaximumLength(256);
        RuleFor(command => command.CoordinatorUsername).NotEmpty().MaximumLength(100);
        // Length floor only — the exact password policy (character classes, breach check) is owned and
        // enforced by Lumen Identity when the account is created; duplicating it here would drift.
        RuleFor(command => command.CoordinatorPassword).NotEmpty().MinimumLength(12);
    }
}

internal sealed class SignupCompanyCommandHandler : ICommandHandler<SignupCompanyCommand, SignupCompanyResult>
{
    private readonly ICompanyRepository _companies;
    private readonly ICompanyOnboardingGateway _onboarding;

    public SignupCompanyCommandHandler(
        ICompanyRepository companies,
        ICompanyOnboardingGateway onboarding)
    {
        _companies = companies;
        _onboarding = onboarding;
    }

    public async Task<SignupCompanyResult> HandleAsync(
        SignupCompanyCommand request,
        CancellationToken cancellationToken = default)
    {
        // Fail fast on duplicates before creating anything, so a rejected signup leaves no partial state.
        if (await _companies.ExistsByNameAsync(request.CompanyName, cancellationToken))
            throw new ConflictException($"A company named '{request.CompanyName}' already exists.");

        if (await _onboarding.CoordinatorEmailExistsAsync(request.CoordinatorEmail, cancellationToken))
            throw new ConflictException($"A user with e-mail '{request.CoordinatorEmail}' already exists.");

        // 1. Coordinator user first: if identity creation fails, no tenant is left behind.
        Guid coordinatorUserId = await _onboarding.CreateCoordinatorAsync(
            request.CoordinatorEmail,
            request.CoordinatorUsername,
            request.CoordinatorPassword,
            cancellationToken);

        // 2. Tenant bound to the coordinator (founding membership + CompanyCreated event).
        //    Persisted by the module's TransactionBehavior calling SaveChangesAsync on the tenancy context.
        Company company = Company.Register(request.CompanyName, coordinatorUserId, request.TaxId);
        await _companies.AddAsync(company, cancellationToken);

        // 3. Company-scoped authorization for the coordinator (idempotent Lumen profile assignment).
        await _onboarding.GrantCoordinatorAccessAsync(coordinatorUserId, company.Id, cancellationToken);

        return new SignupCompanyResult(company.Id, coordinatorUserId);
    }
}
